name: CI
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: com.moonlight_stream.Moonlight.flatpak
        manifest-path: com.moonlight_stream.Moonlight.json
        cache-key: flatpak-builder-${{ github.sha }}